/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * infoMesa.java
 *
 * Created on 27-ago-2010, 19:14:26
 */

package interfaz;

/**
 *
 * @author alex
 */
public class MesaInfo extends javax.swing.JPanel {
    private InfoMesa infomesa;
    private Sala sala;
    /** Creates new form infoMesa */


    public MesaInfo(Sala sala) {
        initComponents();
        this.sala=sala;
    }

    public void setDatos(InfoMesa info) {
        this.infomesa = info;
        String s="";
        for (String n:info.nomJug())
            s+= n + " / ";
        datosmesa.setText("Mesa nº: "+info.getNumMesa()+"\n"+"Jugadores:    "+s);
    }



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        unirse = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        datosmesa = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(153, 153, 153));
        setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        setPreferredSize(new java.awt.Dimension(591, 130));

        unirse.setText("Unir");
        unirse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unirseActionPerformed(evt);
            }
        });

        datosmesa.setColumns(10);
        datosmesa.setRows(3);
        datosmesa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        datosmesa.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jScrollPane1.setViewportView(datosmesa);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 464, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 11, Short.MAX_VALUE)
                .add(unirse)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(unirse))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 73, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void unirseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unirseActionPerformed
        // TODO add your handling code here:
        //Sala.getInstancia().unirMesaDialog(infomesa.getNumMesa());
        sala.unirMesaDialog(infomesa.getNumMesa());
    }//GEN-LAST:event_unirseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea datosmesa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton unirse;
    // End of variables declaration//GEN-END:variables

}
